name: tower_aid
description: TowerAid - emergency response in residential buildings.
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_svg: ^2.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/toweraid_logo.svg
